### ISSUE TITLE
Rosetta-Node-SetUp

### ISSUE THREAD

**Issue by VishwaSh12** [flare-foundation/flare-rosetta#12]
Hi Team,We have started a Rosetta Docker node for Flare network following this ReadMe. 
Can you please let us know the below things:
Is this rosetta flare node an observer type or validator type?
The docker steps mentioned for flare network- I hope it is for mainnet?
Is this docker rosetta node a full node or archival node or pruned node?

**Comment by klemenfn** [comment]
Apologies for late replies

1. Observer
2. mainnet
3. full history/archival
