### ISSUE TITLE
"error":"chains not bootstrapped"

### ISSUE THREAD

**Issue by VishwaSh12** [flare-foundation/flare-rosetta#13]
we are trying to setup rosetta mainnet flare network. 
we started the Rosetta docker node following these commands:
    1. sudo git clone https://github.com/flare-foundation/flare-rosetta.git
    2. cd server
    3. sudo docker build --progress=plain -t my-local-flare-rosetta-image .
        (image were successfully built.)
   4. sudo docker run -d -p 8080:8080 -p 9650:9650 -p 9651:9651 -e NETWORK_ID=flare -v /NewDisk9Machine/node-flare- 
      rosetta/db:/data my-local-flare-rosetta-image 

now we are getting the below error in docker logs:
"error":"chains not bootstrapped"

is this docker run command correct for mainnet?
Note: The node has started accumulating .ldb in the db folder and size of folder is increasing.

Note: we are using Ubuntu V18.04 along with standard SSD disk.

**Comment by klemenfn** [comment]
Apologies for late reply

The behavior is correct, the node needs to bootstrap to full history before rosetta API can be used.

**Comment by dishali2015** [comment]
I pull the flare image from **https://hub.docker.com/r/flarefoundation/flare-rosetta?uuid=2C1344C7-85A0-49DC-B757-9F4A58B4AF4A**
I ran the following command.

docker run -d \
--restart unless-stopped \
--name flare-rosetta \
-e PUBLIC_IP=135.235.218.38 \
-p 8080:8080 \
-p 9650:9650 \
-p 9651:9651 \
-e NETWORK_ID=flare \
-v ~/flare/db:/app/flare/db \
flarefoundation/flare-rosetta:latest

**I got the following logs.**
[go-flare]: [05-20|20:27:27.343] WARN health/health.go:94 failing health check {"reason": {"P":{"message":{"consensus":{},"vm":{"primary-percentConnected":0}},"error":"platform layer is unhealthy reason: connected to 0.000000% of primary network stake; should be connected to at least 80.000000%","timestamp":"2026-05-20T20:27:23.103349257Z","duration":46147,"contiguousFailures":13,"timeOfFirstFailure":"2026-05-20T20:21:23.103508683Z"},"bootstrapped":{"message":["P"],"error":"chains not bootstrapped","timestamp":"2026-05-20T20:27:23.103267503Z","duration":862,"contiguousFailures":13,"timeOfFirstFailure":"2026-05-20T20:21:23.103467385Z"},"database":{"timestamp":"2026-05-20T20:27:23.103299563Z","duration":1062},"diskspace":{"message":{"availableDiskBytes":26748493824},"timestamp":"2026-05-20T20:27:23.103302669Z","duration":2595},"network":{"message":{"connectedPeers":0,"sendFailRate":0,"timeSinceLastMsgReceived":"494252h27m23.103279516s","timeSinceLastMsgSent":"2m10.103279516s"},"error":"network layer is unhealthy reason: not connected to a minimum of 1 peer(s) only 0, no messages from network received in 494252h27m23.103279516s > 1m0s, no messages from network sent in 2m10.103279516s > 1m0s","timestamp":"2026-05-20T20:27:23.103294744Z","duration":26379,"contiguousFailures":14,"timeOfFirstFailure":"2026-05-20T20:20:53.102705809Z"},"router":{"message":{"longestRunningRequest":"0s","outstandingRequests":0},"timestamp":"2026-05-20T20:27:23.10329793Z","duration":2444}}}
[go-flare]: [05-20|20:27:32.392] WARN health/health.go:94 failing health check {"reason

System info : I have created the Ubuntu virtual machine from Azure and have the required access/port.
How to fix the issue?

**Comment by klemenfn** [comment]
Hi. The image on docker hub is outdated, please try https://github.com/flare-foundation/flare-rosetta/pkgs/container/flare-rosetta/747924886?tag=v1.13.0

**Comment by dishali2015** [comment]
@klemenfn I haved used the  image from **https://github.com/flare-foundation/flare-rosetta/pkgs/container/flare-rosetta/747924886?tag=v1.13.0**
I ran the following command.

**sudo docker run -d -p 8080:8080 -p 9650:9650 -p 9651:9651 -e NETWORK_ID=flare -v /ThirdDisk9Machine/node-flare-new/db:/data ghcr.io/flare-foundation/flare-rosetta:v1.13.0**

**I got the following error.**
[go-flare]: [05-21|17:22:11.535] WARN health/health.go:110 failing check {"namespace": "health", "reason": {"P":{"message":{"engine":{"consensus":{},"vm":null},"networking":{"disconnectedValidators":["NodeID-2oZa4x84qqpdNqxKSL3PW28iex3VS1NQT","NodeID-2tpa7L26X8asp9Y5ZpRRtU61iPaooCQ9R","NodeID-4XZ7a7fGCzw6xqMFNQHy46JjUXnnq51Y1","NodeID-4Y6Hxd42SjQ4GNJHYF9GFjKEu2KAYTPDo","NodeID-5bTyYGC8rzxaQ9HFucqRM4aFwYGqT8ciA","NodeID-6FDUTBPEHQmf7S5838REhubwhfPAaJz1i","NodeID-6LWYVCBLcUKW89GXSAscosCAxhyMeoGQR","NodeID-6dBcEfrUMmhTbShvQfiqpybLmvUHtoFem","NodeID-6zMLLn4GvWRApEjAojJNgUEYHxfp2pbPi","NodeID-8bPGGqcmhxL8M7LML5sVvfKRQGDn17uPU","NodeID-95G1AziLcVNUtBHSzc8naSR1bUVvkDEyR","NodeID-Bd4G59NYc1zP9mMVf2yMzaSFA4StQuJn8","NodeID-DMAS3hKKWMydmWGmGd265EYCoV7zFWEHK","NodeID-EQkfps4HcNP5PFmEG2h9QmBT3VsRu9kKu","NodeID-FDQmoefauig76jy7wac8kP5MHdLef9p9o","NodeID-HztJLzW4WwNYteuXpZ8cC9NnZ2cHD1X3Z","NodeID-KrKGrfzP2orrkyiuacKABvyGGty3KffQw","NodeID-LQHTbb1UKdB2mzWRoJWR6ZapvNmkZzWw","NodeID-Lkwe2cpLYh3MwmbsDjuFkJ4ecx5CPxYNJ","NodeID-Lx7BqRD3LQuqZbpJzkc5UDTZb66cpez95"],"percentConnected":0}},"error":"not connected to enough stake: connected to 0.000000%; required at least 80.000000%","timestamp":"2026-05-21T17:22:09.780400038Z","duration":31378,"contiguousFailures":3,"timeOfFirstFailure":"2026-05-21T17:21:09.779993247Z"},"bls":{"message":"node is not a validator","timestamp":"2026-05-21T17:22:09.780367968Z","duration":1202},"bootstrapped":{"message":["11111111111111111111111111111111LpoYY"],"error":"subnets not bootstrapped","timestamp":"2026-05-21T17:22:09.780361476Z","duration":1773,"contiguousFailures":3,"timeOfFirstFailure":"2026-05-21T17:21:09.779991797Z"},"database":{"timestamp":"2026-05-21T17:22:09.780389631Z","duration":20718},"diskspace":{"message":{"availableDiskBytes":6931361792},"timestamp":"2026-05-21T17:22:09.780366135Z","duration":2745},"network":{"message":{"connectedPeers":1,"sendFailRate":0,"timeSinceLastMsgReceived":"780.401097ms","timeSinceLastMsgSent":"780.401097ms"},"timestamp":"2026-05-21T17:22:09.780405846Z","duration":11511},"router":{"message":{"longestRunningRequest":"128.547769ms","outstandingRequests":1},"timestamp":"2026-05-21T17:22:09.780398468Z","duration":4198}}}
