### ISSUE TITLE
Mainnet Node Stopped at "9998651" 22nd June, 2023.

### ISSUE THREAD

**Issue by VishwaSh12** [flare-foundation/flare-rosetta#15]
Hi Team,  I am running a mainnet rosetta docker node using this repository for the past few month.

but since 22nd June, 2023 node has stopped progressing further, from Discord Channel, I get to know that version has been upgraded to v1.7.1805. But I don't see any new release committed to this code base. Let me know how to Proceed further with the docker upgrade.

**Comment by klemenfn** [comment]
Apologies for late reply

v1.7.1806 is the current up to date version
